### ISSUE TITLE
Autodesk Eagle (?)

### ISSUE THREAD

**Issue by mlp6** [mlp6/Fundamentals-BME-Design#11]
Have you seen this: https://www.autodesk.com/products/eagle/overview

**Comment by sphaerobolus** [comment]
Yes. I noticed several months ago that Autodesk had taken Eagle into their portfolio. 

It's probably worth trying Eagle again, if only because I haven't played with it years. It is more widely used than DipTrace.

Presumably students would not have the limitations of the free version, specifically the 80 cm^2 board area restriction. That board is smaller than a lot of our designs.

**Comment by mlp6** [comment]
Agreed.  It looks like they give the same free academic access to the full-version of the software.  This does introduce the entire question of learning industry standard tools vs. tools that might be more accessible for free when you leave Duke.  I'm leaning towards what is most accessible for them to use now, and hope that the difference b/w menu layout, higher-order aspects of the UI don't trip people up when they convert in their post-Duke environment.

**Comment by ericsrichardson** [comment]
I'll leave it to you guys to make the call on PCB stuff :) As for the philosophical question Mark posed, I agree that "most accessible" trumps "most applicable" esp in a learning context because accessibility will drive learning. Both obviously would be best...
